export const columns: ColumnType[] = [
  {
    items: [
      {
        name: "api management service instance",
        slug: "apim-",
        description: "",
        length: "1-50",
        category: Categories.GENERAL,
        learnUrl: "https://learn.microsoft.com/en-us/azure/api-management/",
        terraformUrl: "https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management",
        restrictions: "Alphanumerics and hyphens. Start with letter and end with alphanumeric.",
        resource: "Microsoft.ApiManagement",
        entity: "service",
        scope: "global",
        icon: "",
        code: ""
      },
      {
        name: "managed identity",
        slug: "id-",
        description: "",
        length: "3-128",
        category: Categories.GENERAL,
        learnUrl: "https://learn.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview",
        terraformUrl: "https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/managed_service_identity.html",
        restrictions: "Alphanumerics, hyphens, and underscoresStart with letter or number.",
        resource: "Microsoft.ManagedIdentity",
        entity: "userAssignedIdentities",
        scope: "resource group",
        icon: "",
        code: ""
      },
      {
        name: "management group",
        slug: "mg-",
        description: "",
        length: "",
        category: Categories.GENERAL,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "",
        resource: "",
        entity: "",
        scope: "",
        icon: "",
        code: ""
      },
      {
        name: "policy definition",
        slug: "policy-",
        description: "",
        length: "1-128 display name1-64 resource name",
        category: Categories.GENERAL,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Display name can contain any characters. Resource name can't use:<>*%&:\?. +/ or control characters.  Can't end with period or space.",
        resource: "Microsoft.Authorization",
        entity: "policyDefinitions",
        scope: "scope of definition",
        icon: "",
        code: ""
      },
      {
        name: "resource group",
        slug: "rg-",
        description: "",
        length: "1-90",
        category: Categories.GENERAL,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Underscores, hyphens, periods, parentheses, and letters or digits as defined by the Char. IsLetterOrDigit function. Valid characters are members of the following categories in UnicodeCategory:UppercaseLetter,LowercaseLetter,TitlecaseLetter,ModifierLetter,OtherLetter,DecimalDigitNumber. Can't end with period.",
        resource: "Microsoft.Resources",
        entity: "resourcegroups",
        scope: "subscription",
        icon: "",
        code: ""
      },
    ]
  },
  {
    items: [
      {
        name: "application gateway",
        slug: "agw-",
        description: "",
        length: "1-80",
        category: Categories.NETWORKING,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics, underscores, periods, and hyphens. Start with alphanumeric.  End alphanumeric or underscore.",
        resource: "Microsoft.Network",
        entity: "applicationGateways",
        scope: "resource group",
        icon: "",
        code: ""
      },
      {
        name: "application security group (asg)",
        slug: "asg-",
        description: "",
        length: "1-80",
        category: Categories.NETWORKING,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics, underscores, periods, and hyphens. Start with alphanumeric.  End alphanumeric or underscore.",
        resource: "Microsoft.Network",
        entity: "applicationSecurityGroups",
        scope: "resource group",
        icon: "",
        code: ""
      },
      {
        name: "bastion",
        slug: "bas-",
        description: "",
        length: "1-80",
        category: Categories.NETWORKING,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics, underscores, periods, and hyphens. Start with alphanumeric.  End alphanumeric or underscore.",
        resource: "Microsoft.Network",
        entity: "bastionHosts",
        scope: "resource group",
        icon: "",
        code: ""
      },
      {
        name: "cdn profile",
        slug: "cdnp-",
        description: "",
        length: "1-260",
        category: Categories.NETWORKING,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics and hyphens. Start and end with alphanumeric.",
        resource: "Microsoft.Cdn",
        entity: "profiles",
        scope: "resource group",
        icon: "",
        code: ""
      },
      {
        name: "cdn endpoint",
        slug: "cdne-",
        description: "",
        length: "1-50",
        category: Categories.NETWORKING,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics and hyphens. Start and end with alphanumeric.",
        resource: "Microsoft.Cdn",
        entity: "profiles / endpoints",
        scope: "global",
        icon: "",
        code: ""
      },
      {
        name: "connections",
        slug: "con-",
        description: "",
        length: "1-80",
        category: Categories.NETWORKING,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics, underscores, periods, and hyphens. Start with alphanumeric.  End alphanumeric or underscore.",
        resource: "Microsoft.Network",
        entity: "connections",
        scope: "resource group",
        icon: "",
        code: ""
      },
      {
        name: "dns zone",
        slug: "dnsz-",
        description: "",
        length: "1-63 characters2 to 34 labelsEach label is a set of characters separated by a period. For example, contoso.com has 2 labels.",
        category: Categories.NETWORKING,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Each label can contain alphanumerics, underscores, and hyphens. Each label is separated by a period.",
        resource: "Microsoft.Network",
        entity: "dnsZones",
        scope: "resource group",
        icon: "",
        code: ""
      },
      {
        name: "private dns zone",
        slug: "pdnsz-",
        description: "",
        length: "1-63 characters2 to 34 labelsEach label is a set of characters separated by a period. For example, contoso.com has 2 labels.",
        category: Categories.NETWORKING,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Each label can contain alphanumerics, underscores, and hyphens. Each label is separated by a period.",
        resource: "Microsoft.Network",
        entity: "privateDnsZones",
        scope: "resource group",
        icon: "",
        code: ""
      },
      {
        name: "azure firewall",
        slug: "afw-",
        description: "",
        length: "1-80",
        category: Categories.NETWORKING,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics, underscores, periods, and hyphens. Start with alphanumeric.  End with alphanumeric or underscore.",
        resource: "Microsoft.Network",
        entity: "azureFirewalls",
        scope: "resource group",
        icon: "",
        code: ""
      },
      {
        name: "azure firewall policy",
        slug: "afwp-",
        description: "",
        length: "1-80",
        category: Categories.NETWORKING,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics, underscores, periods, and hyphens. Start with alphanumeric.  End alphanumeric or underscore.",
        resource: "Microsoft.Network",
        entity: "firewallPolicies",
        scope: "resource group",
        icon: "",
        code: ""
      },
    ]
  },
  {
    items: [
      {
        name: "expressroute circuit",
        slug: "erc-",
        description: "",
        length: "1-80",
        category: Categories.NETWORKING,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics, underscores, periods, and hyphens. Start with alphanumeric.  End alphanumeric or underscore.",
        resource: "Microsoft.Network",
        entity: "expressRouteCircuits",
        scope: "resource group",
        icon: "",
        code: ""
      },
      {
        name: "front door instance",
        slug: "fd-",
        description: "",
        length: "5-64",
        category: Categories.NETWORKING,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics and hyphens. Start and end with alphanumeric.",
        resource: "Microsoft.Network",
        entity: "frontDoors",
        scope: "global",
        icon: "",
        code: ""
      },
      {
        name: "front door firewall policy",
        slug: "fdfp-",
        description: "",
        length: "1-128",
        category: Categories.NETWORKING,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics. Start with letter.",
        resource: "Microsoft.Network",
        entity: "frontdoorWebApplicationFirewallPolicies",
        scope: "resource group",
        icon: "",
        code: ""
      },
      {
        name: "load balancer (internal)",
        slug: "lbi-",
        description: "",
        length: "1-80",
        category: Categories.NETWORKING,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics, underscores, periods, and hyphens. Start with alphanumeric.  End alphanumeric or underscore.",
        resource: "Microsoft.Network",
        entity: "loadBalancers",
        scope: "resource group",
        icon: "",
        code: ""
      },
      {
        name: "load balancer (external)",
        slug: "lbe-",
        description: "",
        length: "1-80",
        category: Categories.NETWORKING,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics, underscores, periods, and hyphens. Start with alphanumeric.  End alphanumeric or underscore.",
        resource: "Microsoft.Network",
        entity: "loadBalancers",
        scope: "resource group",
        icon: "",
        code: ""
      },
      {
        name: "load balancer rule",
        slug: "rule-",
        description: "",
        length: "1-80",
        category: Categories.NETWORKING,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics, underscores, periods, and hyphens. Start with alphanumeric.  End alphanumeric or underscore.",
        resource: "Microsoft.Network",
        entity: "loadBalancers / inboundNatRules",
        scope: "load balancer",
        icon: "",
        code: ""
      },
      {
        name: "local network gateway",
        slug: "lgw-",
        description: "",
        length: "1-80",
        category: Categories.NETWORKING,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics, underscores, periods, and hyphens. Start with alphanumeric.  End alphanumeric or underscore.",
        resource: "Microsoft.Network",
        entity: "localNetworkGateways",
        scope: "resource group",
        icon: "",
        code: ""
      },
      {
        name: "nat gateway",
        slug: "ng-",
        description: "",
        length: "1-80",
        category: Categories.NETWORKING,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics, underscores, periods, and hyphens. Start with alphanumeric.  End alphanumeric or underscore.",
        resource: "Microsoft.Network",
        entity: "localNetworkGateways",
        scope: "resource group",
        icon: "",
        code: ""
      },
      {
        name: "network interface (nic)",
        slug: "nic-",
        description: "",
        length: "1-80",
        category: Categories.NETWORKING,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics, underscores, periods, and hyphens. Start with alphanumeric.  End alphanumeric or underscore.",
        resource: "Microsoft.Network",
        entity: "networkInterfaces",
        scope: "resource group",
        icon: "",
        code: ""
      },
      {
        name: "network security group (nsg)",
        slug: "nsg-",
        description: "",
        length: "1-80",
        category: Categories.NETWORKING,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics, underscores, periods, and hyphens. Start with alphanumeric.  End alphanumeric or underscore.",
        resource: "Microsoft.Network",
        entity: "networkSecurityGroups",
        scope: "resource group",
        icon: "",
        code: ""
      },
    ]
  },
  {
    items: [
      {
        name: "nsg security rules",
        slug: "nsgsr-",
        description: "",
        length: "1-80",
        category: Categories.NETWORKING,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics, underscores, periods, and hyphens. Start with alphanumeric.  End alphanumeric or underscore.",
        resource: "Microsoft.Network",
        entity: "networkSecurityGroups / securityRules",
        scope: "network security group",
        icon: "",
        code: ""
      },
      {
        name: "network watcher",
        slug: "nw-",
        description: "",
        length: "1-80",
        category: Categories.NETWORKING,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics, underscores, periods, and hyphens. Start with alphanumeric.  End alphanumeric or underscore.",
        resource: "Microsoft.Network",
        entity: "networkWatchers",
        scope: "resource group",
        icon: "",
        code: ""
      },
      {
        name: "private link",
        slug: "pl-",
        description: "",
        length: "2-64",
        category: Categories.NETWORKING,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics, underscores, periods, and hyphens. Start with alphanumeric.  End alphanumeric or underscore.",
        resource: "Microsoft.Network",
        entity: "privateEndpoints",
        scope: "resource group",
        icon: "",
        code: ""
      },
      {
        name: "public ip address",
        slug: "pip-",
        description: "",
        length: "1-80",
        category: Categories.NETWORKING,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics, underscores, periods, and hyphens. Start with alphanumeric.  End alphanumeric or underscore.",
        resource: "Microsoft.Network",
        entity: "publicIPAddresses",
        scope: "resource group",
        icon: "",
        code: ""
      },
      {
        name: "public ip prefix",
        slug: "ippre-",
        description: "",
        length: "1-80",
        category: Categories.NETWORKING,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics, underscores, periods, and hyphens. Start with alphanumeric.  End alphanumeric or underscore.",
        resource: "Microsoft.Network",
        entity: "publicIPPrefixes",
        scope: "resource group",
        icon: "",
        code: ""
      },
      {
        name: "route filter",
        slug: "rf-",
        description: "",
        length: "1-80",
        category: Categories.NETWORKING,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics, underscores, periods, and hyphens. Start with alphanumeric.  End alphanumeric or underscore.",
        resource: "Microsoft.Network",
        entity: "routeFilters",
        scope: "resource group",
        icon: "",
        code: ""
      },
      {
        name: "route table",
        slug: "rt-",
        description: "",
        length: "1-80",
        category: Categories.NETWORKING,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics, underscores, periods, and hyphens. Start with alphanumeric.  End alphanumeric or underscore.",
        resource: "Microsoft.Network",
        entity: "routeTables",
        scope: "resource group",
        icon: "",
        code: ""
      },
      {
        name: "service endpoint policies",
        slug: "se-",
        description: "",
        length: "1-80",
        category: Categories.NETWORKING,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics, underscores, periods, and hyphens. Start with alphanumeric.  End alphanumeric or underscore.",
        resource: "Microsoft.Network",
        entity: "serviceEndpointPolicies",
        scope: "resource group",
        icon: "",
        code: ""
      },
      {
        name: "traffic manager profile",
        slug: "traf-",
        description: "",
        length: "1-63",
        category: Categories.NETWORKING,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics, hyphens, and periods. Start and end with alphanumeric.",
        resource: "Microsoft.Network",
        entity: "trafficmanagerprofiles",
        scope: "global",
        icon: "",
        code: ""
      },
      {
        name: "user defined route (udr)",
        slug: "udr-",
        description: "",
        length: "1-80",
        category: Categories.NETWORKING,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics, underscores, periods, and hyphens. Start with alphanumeric.  End alphanumeric or underscore.",
        resource: "Microsoft.Network",
        entity: "routeTables / routes",
        scope: "route table",
        icon: "",
        code: ""
      },
    ]
  },
  {
    items: [
      {
        name: "virtual network",
        slug: "vnet-",
        description: "",
        length: "2-64",
        category: Categories.NETWORKING,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics, underscores, periods, and hyphens. Start with alphanumeric.  End alphanumeric or underscore.",
        resource: "Microsoft.Network",
        entity: "virtualNetworks",
        scope: "resource group",
        icon: "",
        code: ""
      },
      {
        name: "subnet",
        slug: "snet-",
        description: "",
        length: "1-80",
        category: Categories.NETWORKING,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics, underscores, periods, and hyphens. Start with alphanumeric.  End alphanumeric or underscore.",
        resource: "Microsoft.Network",
        entity: "virtualnetworks / subnets",
        scope: "virtual network",
        icon: "",
        code: ""
      },
      {
        name: "virtual network peering",
        slug: "peer-",
        description: "",
        length: "1-80",
        category: Categories.NETWORKING,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics, underscores, periods, and hyphens. Start with alphanumeric.  End alphanumeric or underscore.",
        resource: "Microsoft.Network",
        entity: "virtualNetworks / virtualNetworkPeerings",
        scope: "virtual network",
        icon: "",
        code: ""
      },
      {
        name: "virtual wide-area-network",
        slug: "vwan-",
        description: "",
        length: "1-80",
        category: Categories.NETWORKING,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics, underscores, periods, and hyphens. Start with alphanumeric.  End alphanumeric or underscore.",
        resource: "Microsoft.Network",
        entity: "virtualWans",
        scope: "resource group",
        icon: "",
        code: ""
      },
      {
        name: "vpn gateway",
        slug: "vpng-",
        description: "",
        length: "1-80",
        category: Categories.NETWORKING,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics, underscores, periods, and hyphens. Start with alphanumeric.  End alphanumeric or underscore.",
        resource: "Microsoft.Network",
        entity: "vpnGateways",
        scope: "resource group",
        icon: "",
        code: ""
      },
      {
        name: "vpn connection",
        slug: "vcn-",
        description: "",
        length: "1-80",
        category: Categories.NETWORKING,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics, underscores, periods, and hyphens. Start with alphanumeric.  End alphanumeric or underscore.",
        resource: "Microsoft.Network",
        entity: "vpnGateways / vpnConnections",
        scope: "VPN gateway",
        icon: "",
        code: ""
      },
      {
        name: "vpn site",
        slug: "vst-",
        description: "",
        length: "1-80",
        category: Categories.NETWORKING,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics, underscores, periods, and hyphens. Start with alphanumeric.  End alphanumeric or underscore.",
        resource: "Microsoft.Network",
        entity: "vpnSites",
        scope: "resource group",
        icon: "",
        code: ""
      },
      {
        name: "virtual network gateway",
        slug: "vgw-",
        description: "",
        length: "1-80",
        category: Categories.NETWORKING,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics, underscores, periods, and hyphens. Start with alphanumeric.  End alphanumeric or underscore.",
        resource: "Microsoft.Network",
        entity: "virtualNetworkGateways",
        scope: "resource group",
        icon: "",
        code: ""
      },
      {
        name: "web application firewall (waf) policy",
        slug: "waf",
        description: "",
        length: "1-80",
        category: Categories.NETWORKING,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics, underscores, periods, and hyphens. Start with alphanumeric.  End alphanumeric or underscore.",
        resource: "Microsoft.Network",
        entity: "firewallPolicies",
        scope: "resource group",
        icon: "",
        code: ""
      },
      {
        name: "(waf) policy rule group",
        slug: "wafrg",
        description: "",
        length: "1-80",
        category: Categories.NETWORKING,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics, underscores, periods, and hyphens. Start with alphanumeric.  End alphanumeric or underscore.",
        resource: "Microsoft.Network",
        entity: "firewallPolicies / ruleGroups",
        scope: "firewall policy",
        icon: "",
        code: ""
      },
    ]
  },
  {
    items: [
      {
        name: "app service environment",
        slug: "ase-",
        description: "",
        length: "2-60",
        category: Categories.COMPUTEANDWEB,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumeric, hyphens and Unicode characters that can be mapped to PunycodeCan't start or end with hyphen.",
        resource: "Microsoft.Web",
        entity: "sites",
        scope: "global or per domain. See note below.",
        icon: "",
        code: ""
      },
      {
        name: "app service plan",
        slug: "plan-",
        description: "",
        length: "1-40",
        category: Categories.COMPUTEANDWEB,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumeric, hyphens and Unicode characters that can be mapped to Punycode",
        resource: "Microsoft.Web",
        entity: "serverfarms",
        scope: "resource group",
        icon: "",
        code: ""
      },
      {
        name: "availability set",
        slug: "avail-",
        description: "",
        length: "1-80",
        category: Categories.COMPUTEANDWEB,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics, underscores, periods, and hyphens. Start with alphanumeric.  End with alphanumeric or underscore.",
        resource: "Microsoft.Compute",
        entity: "availabilitySets",
        scope: "resource group",
        icon: "",
        code: ""
      },
      {
        name: "azure arc enabled server",
        slug: "arcs-",
        description: "",
        length: "1-40",
        category: Categories.COMPUTEANDWEB,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumeric, hyphens and Unicode characters that can be mapped to Punycode",
        resource: "Microsoft.Web",
        entity: "serverfarms",
        scope: "resource group",
        icon: "",
        code: ""
      },
      {
        name: "azure arc enabled kubernetes cluster",
        slug: "arck",
        description: "",
        length: "1-63",
        category: Categories.COMPUTEANDWEB,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics, underscores, and hyphens. Start and end with alphanumeric.",
        resource: "Microsoft.ContainerService",
        entity: "managedClusters",
        scope: "resource group",
        icon: "",
        code: ""
      },
      {
        name: "cloud service",
        slug: "cld-",
        description: "",
        length: "1-15 See note below.",
        category: Categories.COMPUTEANDWEB,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Can't use spaces, control characters, or these characters: ~ ! @ # $ % ^ & * ( ) = + _ [ ] { } \ | ; : .  ' \". ?Can't start with underscore.  Can't end with period or hyphen.",
        resource: "Microsoft.Compute",
        entity: "cloudservices",
        scope: "resource group",
        icon: "",
        code: ""
      },
      {
        name: "disk encryption set",
        slug: "des",
        description: "",
        length: "1-80",
        category: Categories.COMPUTEANDWEB,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics, underscores, and hyphens.",
        resource: "Microsoft.Compute",
        entity: "diskEncryptionSets",
        scope: "resource group",
        icon: "",
        code: ""
      },
      {
        name: "function app",
        slug: "func-",
        description: "",
        length: "2-60",
        category: Categories.COMPUTEANDWEB,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumeric, hyphens and Unicode characters that can be mapped to PunycodeCan't start or end with hyphen.",
        resource: "Microsoft.Web",
        entity: "sites",
        scope: "global or per domain. See note below.",
        icon: "",
        code: ""
      },
      {
        name: "gallery",
        slug: "gal",
        description: "",
        length: "1-80",
        category: Categories.COMPUTEANDWEB,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics and periods. Start and end with alphanumeric.",
        resource: "Microsoft.Compute",
        entity: "galleries",
        scope: "resource group",
        icon: "",
        code: ""
      },
      {
        name: "managed disk (os)",
        slug: "osdisk",
        description: "",
        length: "1-80",
        category: Categories.COMPUTEANDWEB,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics, underscores, and hyphens.",
        resource: "Microsoft.Compute",
        entity: "disks",
        scope: "resource group",
        icon: "",
        code: ""
      },
    ]
  },
  {
    items: [
      {
        name: "managed disk (data)",
        slug: "disk",
        description: "",
        length: "1-80",
        category: Categories.COMPUTEANDWEB,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics, underscores, and hyphens.",
        resource: "Microsoft.Compute",
        entity: "disks",
        scope: "resource group",
        icon: "",
        code: ""
      },
      {
        name: "notification hubs",
        slug: "ntf-",
        description: "",
        length: "1-260",
        category: Categories.COMPUTEANDWEB,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics, periods, hyphens, and underscores. Start alphanumeric.",
        resource: "Microsoft.NotificationHubs",
        entity: "namespaces / notificationHubs",
        scope: "namespace",
        icon: "",
        code: ""
      },
      {
        name: "notification hubs namespace",
        slug: "ntfns-",
        description: "",
        length: "6-50",
        category: Categories.COMPUTEANDWEB,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics and hyphensStart with letter.  End with alphanumeric.",
        resource: "Microsoft.NotificationHubs",
        entity: "namespaces",
        scope: "global",
        icon: "",
        code: ""
      },
      {
        name: "snapshot",
        slug: "snap-",
        description: "",
        length: "1-80",
        category: Categories.COMPUTEANDWEB,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics, underscores, periods, and hyphens. Start with alphanumeric.  End with alphanumeric or underscore.",
        resource: "Microsoft.Compute",
        entity: "snapshots",
        scope: "resource group",
        icon: "",
        code: ""
      },
      {
        name: "static web app",
        slug: "stapp",
        description: "",
        length: "2-60",
        category: Categories.COMPUTEANDWEB,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumeric, hyphens and Unicode characters that can be mapped to PunycodeCan't start or end with hyphen.",
        resource: "Microsoft.Web",
        entity: "sites",
        scope: "global or per domain. See note below.",
        icon: "",
        code: ""
      },
      {
        name: "virtual machine",
        slug: "vm",
        description: "",
        length: "1-15 (Windows)1-64 (Linux)See note below.",
        category: Categories.COMPUTEANDWEB,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Can't use spaces, control characters, or these characters: ~ ! @ # $ % ^ & * ( ) = + _ [ ] { } \ | ; : .  ' \". ?Windows VMs can't include period or end with hyphen. Linux VMs can't end with period or hyphen.",
        resource: "Microsoft.Compute",
        entity: "virtualMachines",
        scope: "resource group",
        icon: "",
        code: ""
      },
      {
        name: "virtual machine scale set",
        slug: "vmss-",
        description: "",
        length: "1-15 (Windows)1-64 (Linux)See note below.",
        category: Categories.COMPUTEANDWEB,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Can't use spaces, control characters, or these characters: ~ ! @ # $ % ^ & * ( ) = + _ [ ] { } \ | ; : .  ' \". ?Can't start with underscore.  Can't end with period or hyphen.",
        resource: "Microsoft.Compute",
        entity: "virtualMachineScaleSets",
        scope: "resource group",
        icon: "",
        code: ""
      },
      {
        name: "vm storage account",
        slug: "stvm",
        description: "",
        length: "3-24",
        category: Categories.COMPUTEANDWEB,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Lowercase letters and numbers.",
        resource: "Microsoft.Storage",
        entity: "storageAccounts",
        scope: "global",
        icon: "",
        code: ""
      },
      {
        name: "web app",
        slug: "app-",
        description: "",
        length: "2-60",
        category: Categories.COMPUTEANDWEB,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumeric, hyphens and Unicode characters that can be mapped to PunycodeCan't start or end with hyphen.",
        resource: "Microsoft.Web",
        entity: "sites",
        scope: "global or per domain. See note below.",
        icon: "",
        code: ""
      },
    ]
  },
  {
    items: [
      {
        name: "aks cluster",
        slug: "aks-",
        description: "",
        length: "1-63",
        category: Categories.CONTAINERS,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics, underscores, and hyphens. Start and end with alphanumeric.",
        resource: "Microsoft.ContainerService",
        entity: "managedClusters",
        scope: "resource group",
        icon: "",
        code: ""
      },
      {
        name: "container registry",
        slug: "cr",
        description: "",
        length: "5-50",
        category: Categories.CONTAINERS,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics.",
        resource: "Microsoft.ContainerRegistry",
        entity: "registries",
        scope: "global",
        icon: "",
        code: ""
      },
      {
        name: "container instance",
        slug: "ci",
        description: "",
        length: "1-63",
        category: Categories.CONTAINERS,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Lowercase letters, numbers, and hyphens. Can't start or end with hyphen.  Consecutive hyphens aren't allowed.",
        resource: "Microsoft.ContainerInstance",
        entity: "containerGroups",
        scope: "resource group",
        icon: "",
        code: ""
      },
      {
        name: "service fabric cluster",
        slug: "sf-",
        description: "",
        length: "4-23",
        category: Categories.CONTAINERS,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Lowercase letters, numbers, and hyphens. Start with lowercase letter.  End with lowercase letter or number.",
        resource: "Microsoft.ServiceFabric",
        entity: "clusters",
        scope: "region",
        icon: "",
        code: ""
      },
    ]
  },
  {
    items: [
      {
        name: "azure cosmos db database account",
        slug: "cdb-",
        description: "",
        length: "3-44",
        category: Categories.DATABASES,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Lowercase letters, numbers, and hyphens. Start with lowercase letter or number.",
        resource: "Microsoft.DocumentDB",
        entity: "databaseAccounts",
        scope: "global",
        icon: "",
        code: ""
      },
      {
        name: "azure cache for redis instance",
        slug: "redis-",
        description: "",
        length: "1-63",
        category: Categories.DATABASES,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics and hyphens. Start and end with alphanumeric.  Consecutive hyphens not allowed.",
        resource: "Microsoft.Cache",
        entity: "Redis",
        scope: "global",
        icon: "",
        code: ""
      },
      {
        name: "azure sql database server",
        slug: "sql-",
        description: "",
        length: "1-63",
        category: Categories.DATABASES,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Lowercase letters, numbers, and hyphens. Can't start or end with hyphen.",
        resource: "Microsoft.Sql",
        entity: "servers",
        scope: "global",
        icon: "",
        code: ""
      },
      {
        name: "azure sql database",
        slug: "sqldb-",
        description: "",
        length: "1-128",
        category: Categories.DATABASES,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Can't use:<>*%&:\/? or control charactersCan't end with period or space.",
        resource: "Microsoft.Sql",
        entity: "servers / databases",
        scope: "server",
        icon: "",
        code: ""
      },
      {
        name: "synapse analytics",
        slug: "syn",
        description: "",
        length: "1-50",
        category: Categories.DATABASES,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Lowercase letters, hyphens, and numbers. Start and end with letter or number. Can't contain -ondemand",
        resource: "Microsoft.Synapse",
        entity: "workspaces",
        scope: "global",
        icon: "",
        code: ""
      },
      {
        name: "synapse analytics workspace",
        slug: "synw",
        description: "",
        length: "1-50",
        category: Categories.DATABASES,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Lowercase letters, hyphens, and numbers. Start and end with letter or number. Can't contain -ondemand",
        resource: "Microsoft.Synapse",
        entity: "workspaces",
        scope: "global",
        icon: "",
        code: ""
      },
      {
        name: "synapse analytics sql dedicated pool",
        slug: "syndp",
        description: "",
        length: "1-60",
        category: Categories.DATABASES,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Can't contain <>*%&:\/?@- or control characters.  Can't end with .  or space.  Can't contain reserved word.",
        resource: "Microsoft.Synapse",
        entity: "workspaces / sqlPools",
        scope: "workspace",
        icon: "",
        code: ""
      },
      {
        name: "synapse analytics spark pool",
        slug: "synsp",
        description: "",
        length: "1-15",
        category: Categories.DATABASES,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Letters and numbers. Start with letter.  End with letter or number. Can't contain reserved word.",
        resource: "Microsoft.Synapse",
        entity: "workspaces / bigDataPools",
        scope: "workspace",
        icon: "",
        code: ""
      },
    ]
  },
  {
    items: [
      {
        name: "mysql database",
        slug: "mysql-",
        description: "",
        length: "1-63",
        category: Categories.DATABASES,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics and hyphens.",
        resource: "Microsoft.DBforMySQL",
        entity: "servers / databases",
        scope: "servers",
        icon: "",
        code: ""
      },
      {
        name: "postgresql database",
        slug: "psql-",
        description: "",
        length: "1-63",
        category: Categories.DATABASES,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics and hyphens.",
        resource: "Microsoft.DBforPostgreSQL",
        entity: "servers / databases",
        scope: "servers",
        icon: "",
        code: ""
      },
      {
        name: "sql server stretch database",
        slug: "sqlsdb-",
        description: "",
        length: "1-128",
        category: Categories.DATABASES,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Can't use:<>*%&:\/? or control charactersCan't end with period or space.",
        resource: "Microsoft.Sql",
        entity: "servers / databases",
        scope: "server",
        icon: "",
        code: ""
      },
      {
        name: "sql managed instance",
        slug: "sqlmi-",
        description: "",
        length: "1-63",
        category: Categories.DATABASES,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Lowercase letters, numbers, and hyphens.  Can't start or end with hyphen.",
        resource: "Microsoft.Sql",
        entity: "managedInstances",
        scope: "global",
        icon: "",
        code: ""
      },
      {
        name: "storage account",
        slug: "st",
        description: "",
        length: "3-24",
        category: Categories.STORAGE,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Lowercase letters and numbers.",
        resource: "Microsoft.Storage",
        entity: "storageAccounts",
        scope: "global",
        icon: "",
        code: ""
      },
      {
        name: "azure storsimple",
        slug: "ssimp",
        description: "",
        length: "2-50",
        category: Categories.STORAGE,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics and hyphens. Start with letter.  End with alphanumeric.",
        resource: "Microsoft.StorSimple",
        entity: "managers",
        scope: "resource group",
        icon: "",
        code: ""
      },
      {
        name: "azure congnitive search",
        slug: "srch-",
        description: "",
        length: "2-64",
        category: Categories.AIANDML,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics and hyphens. Start and end with alphanumeric.",
        resource: "Microsoft.CognitiveServices",
        entity: "accounts",
        scope: "resource group",
        icon: "",
        code: ""
      },
      {
        name: "azure congnitive services",
        slug: "cog-",
        description: "",
        length: "2-64",
        category: Categories.AIANDML,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics and hyphens. Start and end with alphanumeric.",
        resource: "Microsoft.CognitiveServices",
        entity: "accounts",
        scope: "resource group",
        icon: "",
        code: ""
      },
      {
        name: "azure machine learning workspace",
        slug: "mlw-",
        description: "",
        length: "1-260",
        category: Categories.AIANDML,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Can't use:<>*%&:?+/\\ or control charactersCan't end with a space.",
        resource: "Microsoft.MachineLearning",
        entity: "workspaces",
        scope: "resource group",
        icon: "",
        code: ""
      },
    ]
  },
  {
    items: [
      {
        name: "azure analysis services server",
        slug: "as",
        description: "",
        length: "3-63",
        category: Categories.ANALYTICSANDIOT,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Lowercase letters and numbers. Start with lowercase letter.",
        resource: "Microsoft.AnalysisServices",
        entity: "servers",
        scope: "resource group",
        icon: "",
        code: ""
      },
      {
        name: "azure databricks workspace",
        slug: "dbw-",
        description: "",
        length: "3-64",
        category: Categories.ANALYTICSANDIOT,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics, underscores, and hyphens",
        resource: "Microsoft.Databricks",
        entity: "workspaces",
        scope: "resource group",
        icon: "",
        code: ""
      },
      {
        name: "azure stream analytics",
        slug: "asa-",
        description: "",
        length: "3-63",
        category: Categories.ANALYTICSANDIOT,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics, hyphens, and underscores.",
        resource: "Microsoft.StreamAnalytics",
        entity: "streamingjobs",
        scope: "resource group",
        icon: "",
        code: ""
      },
      {
        name: "azure data explorer cluster",
        slug: "dec",
        description: "",
        length: "4-22",
        category: Categories.ANALYTICSANDIOT,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Lowercase letters and numbers. Start with letter.",
        resource: "Microsoft.Kusto",
        entity: "clusters",
        scope: "global",
        icon: "",
        code: ""
      },
      {
        name: "azure data explorer cluster database",
        slug: "dedb",
        description: "",
        length: "1-260",
        category: Categories.ANALYTICSANDIOT,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics, hyphens, spaces, and periods.",
        resource: "Microsoft.Kusto",
        entity: "/clusters / databases",
        scope: "cluster",
        icon: "",
        code: ""
      },
      {
        name: "azure data factory",
        slug: "adf-",
        description: "",
        length: "3-63",
        category: Categories.ANALYTICSANDIOT,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics and hyphens. Start and end with alphanumeric.",
        resource: "Microsoft.DataFactory",
        entity: "factories",
        scope: "global",
        icon: "",
        code: ""
      },
      {
        name: "data lake store account",
        slug: "dls",
        description: "",
        length: "3-24",
        category: Categories.ANALYTICSANDIOT,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Lowercase letters and numbers.",
        resource: "Microsoft.DataLakeAnalytics",
        entity: "accounts / dataLakeStoreAccounts",
        scope: "account",
        icon: "",
        code: ""
      },
      {
        name: "data lake analytics account",
        slug: "dla",
        description: "",
        length: "3-24",
        category: Categories.ANALYTICSANDIOT,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Lowercase letters and numbers.",
        resource: "Microsoft.DataLakeAnalytics",
        entity: "accounts",
        scope: "global",
        icon: "",
        code: ""
      },
      {
        name: "event hub namespace",
        slug: "evhns-",
        description: "",
        length: "6-50",
        category: Categories.ANALYTICSANDIOT,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics and hyphens. Start with letter.  End with letter or number.",
        resource: "Microsoft.EventHub",
        entity: "namespaces",
        scope: "global",
        icon: "",
        code: ""
      },
      {
        name: "event hub",
        slug: "evh-",
        description: "",
        length: "6-50",
        category: Categories.ANALYTICSANDIOT,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics and hyphens. Start with letter.  End with letter or number.",
        resource: "Microsoft.EventHub",
        entity: "clusters",
        scope: "resource group",
        icon: "",
        code: ""
      },
    ]
  },
  {
    items: [
      {
        name: "event grid",
        slug: "evgd-",
        description: "",
        length: "3-50",
        category: Categories.ANALYTICSANDIOT,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics and hyphens.",
        resource: "Microsoft.EventGrid",
        entity: "domains",
        scope: "resource group",
        icon: "",
        code: ""
      },
      {
        name: "event grid subscription",
        slug: "evgs-",
        description: "",
        length: "3-64",
        category: Categories.ANALYTICSANDIOT,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics and hyphens.",
        resource: "Microsoft.EventGrid",
        entity: "eventSubscriptions",
        scope: "resource group",
        icon: "",
        code: ""
      },
      {
        name: "event grid topic",
        slug: "evgt-",
        description: "",
        length: "3-50",
        category: Categories.ANALYTICSANDIOT,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics and hyphens.",
        resource: "Microsoft.EventGrid",
        entity: "domains / topics",
        scope: "domain",
        icon: "",
        code: ""
      },
      {
        name: "hdinsight - hadoop cluster",
        slug: "hadp-",
        description: "",
        length: "3-59",
        category: Categories.ANALYTICSANDIOT,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics and hyphensStart and end with letter or number.",
        resource: "Microsoft.HDInsight",
        entity: "clusters",
        scope: "global",
        icon: "",
        code: ""
      },
      {
        name: "hdinsight - hbase cluster",
        slug: "hbase-",
        description: "",
        length: "3-59",
        category: Categories.ANALYTICSANDIOT,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics and hyphensStart and end with letter or number.",
        resource: "Microsoft.HDInsight",
        entity: "clusters",
        scope: "global",
        icon: "",
        code: ""
      },
      {
        name: "hdinsight - kafka cluster",
        slug: "kafka-",
        description: "",
        length: "3-59",
        category: Categories.ANALYTICSANDIOT,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics and hyphensStart and end with letter or number.",
        resource: "Microsoft.HDInsight",
        entity: "clusters",
        scope: "global",
        icon: "",
        code: ""
      },
      {
        name: "hdinsight - spark cluster",
        slug: "spark-",
        description: "",
        length: "3-59",
        category: Categories.ANALYTICSANDIOT,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics and hyphensStart and end with letter or number.",
        resource: "Microsoft.HDInsight",
        entity: "clusters",
        scope: "global",
        icon: "",
        code: ""
      },
      {
        name: "hdinsight - storm cluster",
        slug: "storm-",
        description: "",
        length: "3-59",
        category: Categories.ANALYTICSANDIOT,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics and hyphensStart and end with letter or number.",
        resource: "Microsoft.HDInsight",
        entity: "clusters",
        scope: "global",
        icon: "",
        code: ""
      },
      {
        name: "hdinsight - ml services cluster",
        slug: "mls-",
        description: "",
        length: "3-59",
        category: Categories.ANALYTICSANDIOT,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics and hyphensStart and end with letter or number.",
        resource: "Microsoft.HDInsight",
        entity: "clusters",
        scope: "global",
        icon: "",
        code: ""
      },
      {
        name: "iot hub",
        slug: "iot-",
        description: "",
        length: "3-50",
        category: Categories.ANALYTICSANDIOT,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics and hyphens. Can't end with hyphen.",
        resource: "Microsoft.Devices",
        entity: "IotHubs",
        scope: "global",
        icon: "",
        code: ""
      },
    ]
  },
  {
    items: [
      {
        name: "provisioning services",
        slug: "provs-",
        description: "",
        length: "3-64",
        category: Categories.ANALYTICSANDIOT,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics and hyphens. End with alphanumeric.",
        resource: "Microsoft.Devices",
        entity: "provisioningServices",
        scope: "resource group",
        icon: "",
        code: ""
      },
      {
        name: "provisioning services certificate",
        slug: "pcert-",
        description: "",
        length: "1-64",
        category: Categories.ANALYTICSANDIOT,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics, hyphens, periods, and underscores.",
        resource: "Microsoft.Devices",
        entity: "provisioningServices / certificates",
        scope: "provisioningServices",
        icon: "",
        code: ""
      },
      {
        name: "power bi",
        slug: "pbi-",
        description: "",
        length: "3-63",
        category: Categories.ANALYTICSANDIOT,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics and hyphens. Can't start with hyphen.  Can't use consecutive hyphens.",
        resource: "Microsoft.PowerBI",
        entity: "workspaceCollections",
        scope: "region",
        icon: "",
        code: ""
      },
      {
        name: "time series insights",
        slug: "tsi-",
        description: "",
        length: "1-90",
        category: Categories.ANALYTICSANDIOT,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Can't use:'<>%&:\?/# or control characters",
        resource: "Microsoft.TimeSeriesInsights",
        entity: "environments",
        scope: "resource group",
        icon: "",
        code: ""
      },
      {
        name: "virtual desktop host pool",
        slug: "vdp-",
        description: "",
        length: "",
        category: Categories.VIRTUALDESKTOP,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "",
        resource: "",
        entity: "",
        scope: "",
        icon: "",
        code: ""
      },
      {
        name: "virtual desktop application group",
        slug: "vdag-",
        description: "",
        length: "?",
        category: Categories.VIRTUALDESKTOP,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "",
        resource: "",
        entity: "",
        scope: "",
        icon: "",
        code: ""
      },
      {
        name: "virtual desktop workspace",
        slug: "vdws-",
        description: "",
        length: "",
        category: Categories.VIRTUALDESKTOP,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "",
        resource: "",
        entity: "",
        scope: "",
        icon: "",
        code: ""
      },
      {
        name: "app configuration store",
        slug: "appcs-",
        description: "",
        length: "5-50",
        category: Categories.DEVTOOLS,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics, underscores, and hyphens.",
        resource: "Microsoft.AppConfiguration",
        entity: "configurationStores",
        scope: "resource group",
        icon: "",
        code: ""
      },
      {
        name: "signalr",
        slug: "sigr-",
        description: "",
        length: "3-63",
        category: Categories.DEVTOOLS,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics and hyphens. Start with letter.  End with letter or number.",
        resource: "Microsoft.SignalRService",
        entity: "signalR",
        scope: "global",
        icon: "",
        code: ""
      },
    ]
  },
  {
    items: [
      {
        name: "integration account",
        slug: "ia-",
        description: "",
        length: "1-80",
        category: Categories.INTEGRATION,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics, hyphens, underscores, periods, and parenthesis.",
        resource: "Microsoft.Logic",
        entity: "integrationAccounts",
        scope: "resource group",
        icon: "",
        code: ""
      },
      {
        name: "logic apps",
        slug: "logic-",
        description: "",
        length: "1-43",
        category: Categories.INTEGRATION,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics, hyphens, underscores, periods, and parenthesis.",
        resource: "Microsoft.Logic",
        entity: "workflows",
        scope: "resource group",
        icon: "",
        code: ""
      },
      {
        name: "service bus",
        slug: "sb-",
        description: "",
        length: "6-50",
        category: Categories.INTEGRATION,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics and hyphens. Start with a letter.  End with a letter or number. For more information, see Create namespace.",
        resource: "Microsoft.ServiceBus",
        entity: "namespaces",
        scope: "global",
        icon: "",
        code: ""
      },
      {
        name: "service bus queue",
        slug: "sbq-",
        description: "",
        length: "1-260",
        category: Categories.INTEGRATION,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics, periods, hyphens, underscores, and slashes. Start and end with alphanumeric.",
        resource: "Microsoft.ServiceBus",
        entity: "namespaces / queues",
        scope: "namespace",
        icon: "",
        code: ""
      },
      {
        name: "service bus topic",
        slug: "sbt-",
        description: "",
        length: "1-260",
        category: Categories.INTEGRATION,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics, periods, hyphens, underscores, and slashes. Start and end with alphanumeric.",
        resource: "Microsoft.ServiceBus",
        entity: "namespaces / topics",
        scope: "namespace",
        icon: "",
        code: ""
      },
      {
        name: "azure migrate project",
        slug: "migr-",
        description: "",
        length: "2-57",
        category: Categories.MIGRATION,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics, hyphens, periods, and underscores. Start with alphanumeric.",
        resource: "Microsoft.DataMigration",
        entity: "services / projects",
        scope: "service",
        icon: "",
        code: ""
      },
      {
        name: "database migration service instance",
        slug: "dms-",
        description: "",
        length: "2-62",
        category: Categories.MIGRATION,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics, hyphens, periods, and underscores. Start with alphanumeric.",
        resource: "Microsoft.DataMigration",
        entity: "services",
        scope: "resource group",
        icon: "",
        code: ""
      },
      {
        name: "recovery services vault",
        slug: "rsv-",
        description: "",
        length: "2-50",
        category: Categories.MIGRATION,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics and hyphens. Start with letter.",
        resource: "Microsoft.RecoveryServices",
        entity: "vaults",
        scope: "resource group",
        icon: "",
        code: ""
      },
    ]
  },
  {
    items: [
      {
        name: "automation account",
        slug: "aa-",
        description: "",
        length: "6-50",
        category: Categories.MANAGEMENT,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics and hyphens. Start with letter and end with alphanumeric.",
        resource: "Microsoft.Automation",
        entity: "automationAccounts",
        scope: "resource group & region (See note below)",
        icon: "",
        code: ""
      },
      {
        name: "application insights",
        slug: "appi-",
        description: "",
        length: "1-260",
        category: Categories.MANAGEMENT,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Can't use:%&\?/ or control characters Can't end with space or period.",
        resource: "Microsoft.Insights",
        entity: "components",
        scope: "resource group",
        icon: "",
        code: ""
      },
      {
        name: "azure monitor action group",
        slug: "ag-",
        description: "",
        length: "1-260",
        category: Categories.MANAGEMENT,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Can't use::<>+/&%\? or control characters Can't end with space or period.",
        resource: "Microsoft.Insights",
        entity: "actionGroups",
        scope: "resource group",
        icon: "",
        code: ""
      },
      {
        name: "azure purview instances",
        slug: "pview-",
        description: "",
        length: "6-50",
        category: Categories.MANAGEMENT,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "",
        resource: "",
        entity: "",
        scope: "",
        icon: "",
        code: ""
      },
      {
        name: "blueprint",
        slug: "bp-",
        description: "",
        length: "90",
        category: Categories.MANAGEMENT,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics, underscores, and hyphens.",
        resource: "Microsoft.Blueprint",
        entity: "blueprint",
        scope: "Management groups, Subscriptions, Resource groups",
        icon: "",
        code: ""
      },
      {
        name: "blueprint assignment",
        slug: "bps-",
        description: "",
        length: "90",
        category: Categories.MANAGEMENT,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics, underscores, and hyphens.",
        resource: "Microsoft.Blueprint",
        entity: "blueprintAssignments",
        scope: "Management groups, Subscriptions, Resource groups",
        icon: "",
        code: ""
      },
      {
        name: "key vault",
        slug: "kv-",
        description: "",
        length: "3-24",
        category: Categories.MANAGEMENT,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics and hyphens. Start with letter.  End with letter or digit.  Can't contain consecutive hyphens.",
        resource: "Microsoft.KeyVault",
        entity: "vaults",
        scope: "global",
        icon: "",
        code: ""
      },
      {
        name: "log analytics workspace",
        slug: "log-",
        description: "",
        length: "4-63",
        category: Categories.MANAGEMENT,
        learnUrl: "",
        terraformUrl: "",
        restrictions: "Alphanumerics and hyphens. Start and end with alphanumeric.",
        resource: "Microsoft.OperationalInsights",
        entity: "workspaces",
        scope: "resource group",
        icon: "",
        code: ""
      },
    ]
  },
];