icons = {
    'api management service instance': '/icons/integration/api-management.png',
    'managed identity': '/icons/identity/managed-identities.png',
    'management group': '/icons/general/managementgroups.png',
    'policy definition': '/icons/general/information.png', 
    'resource group': '/icons/general/resourcegroups.png',
    'application gateway': '/icons/network/application-gateway.png',
    'application security group (asg)': '/icons/network/application-security-groups.png',
    'bastion': '/icons/network/bastion.png',
    'cdn profile': '/icons/network/cdn-profiles.png',
    'cdn endpoint': '/icons/network/cdn-profiles.png',
    'connections': '/icons/network/connections.png',
    'dns zone': '/icons/network/dns-zones.png',
    'private dns zone': '/icons/network/dns-private-zones.png',
    'azure firewall': '/icons/network/firewall.png',
    'azure firewall policy': '/icons/security/defender.png',
    'expressroute circuit': '/icons/network/expressroute-circuits.png',
    'front door instance': '/icons/network/front-doors.png',
    'front door firewall policy': '/icons/network/front-doors.png',
    'load balancer (internal)': '/icons/network/load-balancers.png',
    'load balancer (external)': '/icons/network/load-balancers.png',
    'load balancer rule': '/icons/network/load-balancers.png',
    'local network gateway': '/icons/network/local-network-gateways.png',
    'nat gateway': '/icons/network/network-watcher.png',
    'network interface (nic)': '/icons/network/network-interfaces.png',
    'network security group (nsg)': '/icons/network/network-security-groups-classic.png',
    'nsg security rules': '/icons/network/network-security-groups-classic.png',
    'network watcher': '/icons/network/network-watcher.png',
    'private link': '/icons/network/network-interfaces.png',
    'public ip address': '/icons/network/public-ip-addresses.png',
    'public ip prefix': '/icons/network/public-ip-addresses.png',
    'route filter': '/icons/network/route-filters.png',
    'route table': '/icons/network/route-tables.png',
    'service endpoint policies': '/icons/network/service-endpoint-policies.png',
    'traffic manager profile': '/icons/network/traffic-manager-profiles.png',
    'user defined route (udr)': '/icons/network/route-tables.png',
    'virtual network': '/icons/network/virtual-networks.png',
    'subnet': '/icons/network/subnets.png',
    'virtual network peering': '/icons/network/virtual-networks.png',
    'virtual wide-area-network': '/icons/network/virtual-wans.png',
    'vpn gateway': '/icons/network/virtual-network-gateways.png',
    'vpn connection': '/icons/network/virtual-network-gateways.png',
    'vpn site': '/icons/network/virtual-network-gateways.png',
    'virtual network gateway': '/icons/network/virtual-network-gateways.png',
    'web application firewall (waf) policy': '/icons/security/firewall.png',
    '(waf) policy rule group': '/icons/security/firewall.png',
    'app service environment': '/icons/web/app-service-environments.png',
    'app service plan': '/icons/web/app-service-plans.png',
    'availability set': '/icons/compute/availability-sets.png',
    'azure arc enabled server': '/icons/compute/vm.png',
    'azure arc enabled kubernetes cluster': '/icons/compute/kubernetes-services.png',
    'cloud service': '/icons/compute/cloud-services.png',
    'disk encryption set': '/icons/compute/disk-encryption-sets.png',
    'function app': '/icons/compute/function-apps.png',
    'gallery': '/icons/compute/shared-image-galleries.png',
    'managed disk (os)': '/icons/compute/disks.png',
    'managed disk (data)': '/icons/compute/disks.png',
    'notification hubs': '/icons/mobile/notification-hubs.png',
    'notification hubs namespace': '/icons/mobile/notification-hubs.png',
    'snapshot': '/icons/compute/disk-snapshots.png',
    'static web app': '/icons/web/app-services.png',
    'virtual machine': '/icons/compute/vm.png',
    'virtual machine scale set': '/icons/compute/vm-scale-set.png',
    'vm storage account': '/icons/storage/storage-accounts.png',
    'web app': '/icons/web/app-services.png',
    'aks cluster': '/icons/compute/kubernetes-services.png',
    'container registry': '/icons/compute/container-registries.png',
    'container instance': '/icons/compute/container-instances.png',
    'service fabric cluster': '/icons/compute/service-fabric-clusters.png',
    'azure cosmos db database account': '/icons/database/cosmos-db.png',
    'azure cache for redis instance': '/icons/database/cache-for-redis.png',
    'azure sql database server': '/icons/database/sql-servers.png',
    'azure sql database': '/icons/database/sql-databases.png',
    'synapse analytics': '/icons/database/synapse-analytics.png',
    'synapse analytics workspace': '/icons/analytics/synapse-analytics.png',
    'synapse analytics sql dedicated pool': '/icons/analytics/synapse-analytics.png',
    'synapse analytics spark pool': '/icons/analytics/synapse-analytics.png',
    'mysql database': '/icons/database/database-for-mysql-servers.png',
    'postgresql database': '/icons/database/database-for-postgresql-servers.png',
    'sql server stretch database': '/icons/database/sql-server-stretch-databases.png',
    'sql managed instance': '/icons/database/sql-managed-instances.png',
    'storage account': '/icons/storage/storage-accounts.png',
    'azure storsimple': '/icons/storage/storsimple-device-managers.png',
    'azure congnitive search': '/icons/web/search.png',
    'azure congnitive services': '/icons/ml/cognitive-services.png',
    'azure machine learning workspace': '/icons/ml/machine-learning-service-workspaces.png',
    'azure analysis services server': '/icons/analytics/analysis-services.png',
    'azure databricks workspace': '/icons/analytics/databricks.png',
    'azure stream analytics': '/icons/analytics/stream-analytics-jobs.png',
    'azure data explorer cluster': '/icons/analytics/data-explorer-clusters.png',
    'azure data explorer cluster database': '/icons/analytics/data-explorer-clusters.png',
    'azure data factory': '/icons/analytics/data-factories.png',
    'data lake store account': '/icons/database/data-lake.png',
    'data lake analytics account': '/icons/analytics/data-lake-analytics.png',
    "event hub namespace": "/icons/analytics/event-hubs.png",
    "event hub": "/icons/analytics/event-hubs.png",
    "event grid": "/icons/integration/event-grid-topics.png",
    "event grid subscription": "/icons/integration/event-grid-subscriptions.png",
    "event grid topic": "/icons/integration/event-grid-topics.png",
    "hdinsight - hadoop cluster": "/icons/analytics/hdinsightclusters.png",
    "hdinsight - hbase cluster": "/icons/analytics/hdinsightclusters.png",
    "hdinsight - kafka cluster": "/icons/analytics/hdinsightclusters.png",
    "hdinsight - spark cluster": "/icons/analytics/hdinsightclusters.png",
    "hdinsight - storm cluster": "/icons/analytics/hdinsightclusters.png",
    "hdinsight - ml services cluster": "/icons/analytics/hdinsightclusters.png",
    "iot hub": "/icons/iot/iot-hub.png",
    "provisioning services": "/icons/iot/device-provisioning-services.png",
    "provisioning services certificate": "/icons/iot/device-provisioning-services.png",
    "power bi": "/icons/general/allresources.png",
    "time series insights": "/icons/iot/time-series-insights-environments.png",
    "virtual desktop host pool": "/icons/compute/cloudsimple-virtual-machines.png",
    "virtual desktop application group": "/icons/compute/cloudsimple-virtual-machines.png",
    "virtual desktop workspace": "/icons/compute/workspaces.png",
    "app configuration store": "/icons/integration/app-configuration.png",
    "signalr": "/icons/web/signalr.png",
    "integration account": "/icons/integration/integration-accounts.png",
    "logic apps": "/icons/integration/logic-apps.png",
    "service bus": "/icons/integration/service-bus.png",
    "service bus queue": "/icons/integration/service-bus.png",
    "service bus topic": "/icons/integration/service-bus.png",
    "azure migrate project": "/icons/migration/migration-projects.png",
    "database migration service instance": "/icons/migration/database-migration-services.png",
    "recovery services vault": "/icons/migration/recovery-services-vaults.png",
    "automation account": "/icons/compute/automanaged-vm.png",
    "application insights": "/icons/devops/application-insights.png",
    "azure monitor action group": "/icons/general/allresources.png",
    "azure purview instances": "/icons/general/allresources.png",
    "blueprint": "/icons/general/allresources.png",
    "blueprint assignment": "/icons/general/allresources.png",
    "key vault": "/icons/security/key-vaults.png",
    "log analytics workspace": "/icons/analytics/log-analytics-workspaces.png"
}

